// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://runeterygcqdzrdaetds.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ1bmV0ZXJ5Z2NxZHpyZGFldGRzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwNTg1OTQsImV4cCI6MjA2NzYzNDU5NH0.Eiihld8Nv5hJnZzrV0OKDV18DrzRm8fHbh4oKQxnb54";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});